import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Some kind of thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          Hola, Próximo Mundo
          <Link href="/about">ABOUT?!</Link>
          <Link href="/products">PRODUCTS?!?!!</Link>
        </div>
      </main>
    </>
  )
}

export default Home;